"""
app/agents/personas/__init__.py
Mapa de perfis → prompts por idioma (PT, EN, ES).
"""
from app.agents.personas.investidor import INVESTIDOR_PROMPT_PT, INVESTIDOR_PROMPT_EN, INVESTIDOR_PROMPT_ES
from app.agents.personas.pesquisador import PESQUISADOR_PROMPT_PT, PESQUISADOR_PROMPT_EN, PESQUISADOR_PROMPT_ES
from app.agents.personas.startup import STARTUP_PROMPT_PT, STARTUP_PROMPT_EN, STARTUP_PROMPT_ES
from app.agents.personas.corporacao import CORPORACAO_PROMPT_PT, CORPORACAO_PROMPT_EN, CORPORACAO_PROMPT_ES
from app.agents.personas.governo import GOVERNO_PROMPT_PT, GOVERNO_PROMPT_EN, GOVERNO_PROMPT_ES
from app.agents.personas.aceleradora import ACELERADORA_PROMPT_PT, ACELERADORA_PROMPT_EN, ACELERADORA_PROMPT_ES
from app.agents.personas.universidade import UNIVERSIDADE_PROMPT_PT, UNIVERSIDADE_PROMPT_EN, UNIVERSIDADE_PROMPT_ES
from app.agents.personas.mentor import MENTOR_PROMPT_PT, MENTOR_PROMPT_EN, MENTOR_PROMPT_ES
from app.agents.personas.profissional import PROFISSIONAL_PROMPT_PT, PROFISSIONAL_PROMPT_EN, PROFISSIONAL_PROMPT_ES

# ── Mapa: (perfil_normalizado, idioma) → prompt ───────────────────────────────
AGENT_PROMPTS_BY_LANG: dict[str, dict[str, str]] = {
    "PT": {
        "Investidor": INVESTIDOR_PROMPT_PT,
        "investidor": INVESTIDOR_PROMPT_PT,
        "Investor": INVESTIDOR_PROMPT_PT,
        "Angel": INVESTIDOR_PROMPT_PT,
        "Anjo": INVESTIDOR_PROMPT_PT,
        "Fundo": INVESTIDOR_PROMPT_PT,
        "Pesquisador ou Cientista": PESQUISADOR_PROMPT_PT,
        "pesquisador ou cientista": PESQUISADOR_PROMPT_PT,
        "Pesquisador": PESQUISADOR_PROMPT_PT,
        "Cientista": PESQUISADOR_PROMPT_PT,
        "Professor": PESQUISADOR_PROMPT_PT,
        "Doutor": PESQUISADOR_PROMPT_PT,
        "Startup": STARTUP_PROMPT_PT,
        "startup": STARTUP_PROMPT_PT,
        "Founder": STARTUP_PROMPT_PT,
        "Empreendedor": STARTUP_PROMPT_PT,
        "CEO": STARTUP_PROMPT_PT,
        "CTO": STARTUP_PROMPT_PT,
        "Corporação": CORPORACAO_PROMPT_PT,
        "corporacao": CORPORACAO_PROMPT_PT,
        "Empresa": CORPORACAO_PROMPT_PT,
        "Inovação Aberta": CORPORACAO_PROMPT_PT,
        "Indústria": CORPORACAO_PROMPT_PT,
        "Corporate": CORPORACAO_PROMPT_PT,
        "Instituição do Governo": GOVERNO_PROMPT_PT,
        "Governo": GOVERNO_PROMPT_PT,
        "Órgão Público": GOVERNO_PROMPT_PT,
        "Prefeitura": GOVERNO_PROMPT_PT,
        "Secretaria": GOVERNO_PROMPT_PT,
        "Ministério": GOVERNO_PROMPT_PT,
        "Aceleradora / Incubadora / Hub de Inovação": ACELERADORA_PROMPT_PT,
        "Aceleradora": ACELERADORA_PROMPT_PT,
        "Incubadora": ACELERADORA_PROMPT_PT,
        "Hub": ACELERADORA_PROMPT_PT,
        "Parque Tecnológico": ACELERADORA_PROMPT_PT,
        "Universidade ou Instituição de Pesquisa": UNIVERSIDADE_PROMPT_PT,
        "Universidade": UNIVERSIDADE_PROMPT_PT,
        "Faculdade": UNIVERSIDADE_PROMPT_PT,
        "Instituto": UNIVERSIDADE_PROMPT_PT,
        "ICT": UNIVERSIDADE_PROMPT_PT,
        "Mentor ou Consultor": MENTOR_PROMPT_PT,
        "Mentor": MENTOR_PROMPT_PT,
        "Consultor": MENTOR_PROMPT_PT,
        "Advisor": MENTOR_PROMPT_PT,
        "Conselheiro": MENTOR_PROMPT_PT,
        "Profissional Especializado ou Técnico": PROFISSIONAL_PROMPT_PT,
        "Profissional": PROFISSIONAL_PROMPT_PT,
        "Técnico": PROFISSIONAL_PROMPT_PT,
        "Desenvolvedor": PROFISSIONAL_PROMPT_PT,
        "Engenheiro": PROFISSIONAL_PROMPT_PT,
        "Designer": PROFISSIONAL_PROMPT_PT,
    },
    "EN": {
        "Investidor": INVESTIDOR_PROMPT_EN,
        "Investor": INVESTIDOR_PROMPT_EN,
        "Angel": INVESTIDOR_PROMPT_EN,
        "Fund": INVESTIDOR_PROMPT_EN,
        "Venture Capital": INVESTIDOR_PROMPT_EN,
        "VC": INVESTIDOR_PROMPT_EN,
        "Pesquisador ou Cientista": PESQUISADOR_PROMPT_EN,
        "Researcher": PESQUISADOR_PROMPT_EN,
        "Scientist": PESQUISADOR_PROMPT_EN,
        "Professor": PESQUISADOR_PROMPT_EN,
        "PhD": PESQUISADOR_PROMPT_EN,
        "Startup": STARTUP_PROMPT_EN,
        "Founder": STARTUP_PROMPT_EN,
        "Entrepreneur": STARTUP_PROMPT_EN,
        "CEO": STARTUP_PROMPT_EN,
        "CTO": STARTUP_PROMPT_EN,
        "Corporação": CORPORACAO_PROMPT_EN,
        "Corporation": CORPORACAO_PROMPT_EN,
        "Company": CORPORACAO_PROMPT_EN,
        "Enterprise": CORPORACAO_PROMPT_EN,
        "Empresa": CORPORACAO_PROMPT_EN,
        "Open Innovation": CORPORACAO_PROMPT_EN,
        "Instituição do Governo": GOVERNO_PROMPT_EN,
        "Government": GOVERNO_PROMPT_EN,
        "Public Institution": GOVERNO_PROMPT_EN,
        "Agency": GOVERNO_PROMPT_EN,
        "Ministry": GOVERNO_PROMPT_EN,
        "Aceleradora / Incubadora / Hub de Inovação": ACELERADORA_PROMPT_EN,
        "Accelerator": ACELERADORA_PROMPT_EN,
        "Incubator": ACELERADORA_PROMPT_EN,
        "Hub": ACELERADORA_PROMPT_EN,
        "Innovation Hub": ACELERADORA_PROMPT_EN,
        "Universidade ou Instituição de Pesquisa": UNIVERSIDADE_PROMPT_EN,
        "University": UNIVERSIDADE_PROMPT_EN,
        "Research Institution": UNIVERSIDADE_PROMPT_EN,
        "College": UNIVERSIDADE_PROMPT_EN,
        "Institute": UNIVERSIDADE_PROMPT_EN,
        "Mentor ou Consultor": MENTOR_PROMPT_EN,
        "Mentor": MENTOR_PROMPT_EN,
        "Consultant": MENTOR_PROMPT_EN,
        "Advisor": MENTOR_PROMPT_EN,
        "Profissional Especializado ou Técnico": PROFISSIONAL_PROMPT_EN,
        "Professional": PROFISSIONAL_PROMPT_EN,
        "Specialist": PROFISSIONAL_PROMPT_EN,
        "Developer": PROFISSIONAL_PROMPT_EN,
        "Engineer": PROFISSIONAL_PROMPT_EN,
        "Designer": PROFISSIONAL_PROMPT_EN,
    },
    "ES": {
        "Investidor": INVESTIDOR_PROMPT_ES,
        "Inversor": INVESTIDOR_PROMPT_ES,
        "Investor": INVESTIDOR_PROMPT_ES,
        "Angel": INVESTIDOR_PROMPT_ES,
        "Fondo": INVESTIDOR_PROMPT_ES,
        "Pesquisador ou Cientista": PESQUISADOR_PROMPT_ES,
        "Investigador": PESQUISADOR_PROMPT_ES,
        "Científico": PESQUISADOR_PROMPT_ES,
        "Profesor": PESQUISADOR_PROMPT_ES,
        "Doctor": PESQUISADOR_PROMPT_ES,
        "Startup": STARTUP_PROMPT_ES,
        "Founder": STARTUP_PROMPT_ES,
        "Emprendedor": STARTUP_PROMPT_ES,
        "CEO": STARTUP_PROMPT_ES,
        "CTO": STARTUP_PROMPT_ES,
        "Corporação": CORPORACAO_PROMPT_ES,
        "Corporación": CORPORACAO_PROMPT_ES,
        "Empresa": CORPORACAO_PROMPT_ES,
        "Innovación Abierta": CORPORACAO_PROMPT_ES,
        "Industria": CORPORACAO_PROMPT_ES,
        "Instituição do Governo": GOVERNO_PROMPT_ES,
        "Gobierno": GOVERNO_PROMPT_ES,
        "Institución Pública": GOVERNO_PROMPT_ES,
        "Agencia": GOVERNO_PROMPT_ES,
        "Ministerio": GOVERNO_PROMPT_ES,
        "Aceleradora / Incubadora / Hub de Inovação": ACELERADORA_PROMPT_ES,
        "Aceleradora": ACELERADORA_PROMPT_ES,
        "Incubadora": ACELERADORA_PROMPT_ES,
        "Hub": ACELERADORA_PROMPT_ES,
        "Parque Tecnológico": ACELERADORA_PROMPT_ES,
        "Universidade ou Instituição de Pesquisa": UNIVERSIDADE_PROMPT_ES,
        "Universidad": UNIVERSIDADE_PROMPT_ES,
        "Institución de Investigación": UNIVERSIDADE_PROMPT_ES,
        "Facultad": UNIVERSIDADE_PROMPT_ES,
        "Instituto": UNIVERSIDADE_PROMPT_ES,
        "Mentor ou Consultor": MENTOR_PROMPT_ES,
        "Mentor": MENTOR_PROMPT_ES,
        "Consultor": MENTOR_PROMPT_ES,
        "Asesor": MENTOR_PROMPT_ES,
        "Profissional Especializado ou Técnico": PROFISSIONAL_PROMPT_ES,
        "Profesional": PROFISSIONAL_PROMPT_ES,
        "Técnico": PROFISSIONAL_PROMPT_ES,
        "Desarrollador": PROFISSIONAL_PROMPT_ES,
        "Ingeniero": PROFISSIONAL_PROMPT_ES,
        "Diseñador": PROFISSIONAL_PROMPT_ES,
    },
}

# Aliases para compatibilidade
AGENT_PROMPTS = AGENT_PROMPTS_BY_LANG["PT"]
DEFAULT_PROMPT = INVESTIDOR_PROMPT_PT
